version: "3"
services:
  betty:
    image: eightlimbed/betty-docker
    command: tail -f /dev/null
    volumes:
      - ".:/root/"
  shellcheck:
    image: koalaman/shellcheck-alpine
    #command: shellcheck
    command: tail -f /dev/null 
    working_dir: /root
    volumes:
      - ".:/root/"
  pep8:
    image: romalms10/pep8
    command: tail -f /dev/null
    volumes:
      - ".:/root/"
